In [1]:
import   numpy as np


In [2]:
# 通过列表创建数组
array01=[1,2,3,4]
array-np.array(array01) 

array([1, 2, 3, 4])

In [5]:
# 创建二维数组
#创建数组 arange
s=np.arange(5,10,2)
print(s)

[5 7 9]


In [7]:
np.zeros(19,dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int8)

In [16]:
array04=[[1,2,3,4],[5,6,7,8]]
arraytest=np.array(array04)
# 元素中占用字符的大小
arraytest.itemsize

4

In [18]:
array05=[[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[6,7,8,9]]]

a05=np.array(array05)
print(a05)

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [6 7 8 9]]]


array06=[("zh",[1,2,4],15),("zs",[2,3,4],17),("az",[2,3,4],12)] 
np.array(array06,dtype="U3,3int32,int32")


In [28]:
list7=[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
array7=np.array(list7)
array7[0:1,0:1,1:2]
array7[0,0,1]



2